{% set name = "echoregions" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/echoregions-{{ version }}.tar.gz
  sha256: ff6c2489321b2e12c51a922476255e9ac906484282376826c55e12ccb3203fb0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=48
    - setuptools-scm >=4,<6
    - setuptools_scm_git_archive
    - wheel >=0.29.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.21.0
    - pandas >=2.0.0
    - matplotlib-base
    - regionmask >=0.8.0
    - shapely >=2.0.0
    - zarr
    - netcdf4
    - scipy

test:
  imports:
    - echoregions
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/OSOceanAcoustics/echoregions
  summary: Parsers and functions for working with EVR and EVL files
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ctuguinay
    - leewujung
