{% set name = "echoregions" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/echoregions-{{ version }}.tar.gz
  sha256: 4dbd0d7ac1cab81b419179804c1f9e92ecef7ee068a706355086710f89ab0bb8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=48
    - setuptools-scm >=4,<6
    - setuptools_scm_git_archive
    - wheel >=0.29.0
    - pip
  run:
    - python >={{ python_min }},<3.13
    - numpy >=1.21.0
    - pandas >=2.0.0
    - matplotlib-base
    - regionmask >=0.8.0
    - shapely >=2.0.0
    - zarr >=2,<3
    - netcdf4
    - scipy <1.15.2
    - xarray >=2024.11.0
    - dask
test:
  imports:
    - echoregions
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/OSOceanAcoustics/echoregions
  summary: Interfacing water column sonar data with annotations and labels
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ctuguinay
    - leewujung
