{% set name = "echoregions" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/echoregions-{{ version }}.tar.gz
  sha256: 882564517ce2b5e85d7a308df1a36d063d5836cac263b602a50b7c112b698444

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=48
    - setuptools-scm >=4,<6
    - setuptools_scm_git_archive
    - wheel >=0.29.0
    - pip
  run:
    - python >=3.9
    - numpy >=1.21.0
    - pandas >=2.0.0
    - matplotlib-base
    - regionmask >=0.8.0
    - shapely >=2.0.0
    - zarr
    - netcdf4
    - scipy

test:
  imports:
    - echoregions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OSOceanAcoustics/echoregions
  summary: Parsers and functions for working with EVR and EVL files
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ctuguinay
